sudo: false

language: go

go:
 - tip

# Required for coverage, and testing.
#before_install:
# - go get golang.org/x/tools/cmd/cover
# - go get github.com/mattn/goveralls

script:
 - go build -x -v ./cmd/main.go
 - go test -a -x -v *.go

 notifications:
  email:
    recipients:
      - binaryplease@gmail.com
