sudo: false

language: go

go:
 - tip

# Required for coverage, and testing.
before_install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

# Get deps, build, test, and ensure the code is gofmt'ed.
# If we are building as gonum, then we have access to the coveralls api key, so we can run coverage as well.
script:
# - go get -d -t -v .
 - go build -x -v ./cmd/main.go
 - go test -a -x -v *.go
